  // RESERVED
#define _k20 "if"
#define _k40 "else"
#define _k50 "while"
#define _k21 "do"
#define _k30 "for"
#define _k22 "in"
#define _k41 "with"
#define _k80 "continue"
#define _k60 "switch"
#define _k42 "case"
#define _k51 "break"
#define _k70 "default"
#define _k52 "yield"
#define _k31 "try"
#define _k61 "chatch"
#define _k71 "finally"
#define _k53 "throw"
#define _k32 "var"
#define _k54 "const"
#define _k81 "function"
#define _k43 "void"
#define _k62 "typeof"
#define _k55 "class"
#define _k33 "new"
#define _k100 "instanceof"
#define _k56 "super"
#define _k44 "this"
#define _k63 "import"
  //  LITERALS
#define _k45 "null"
#define _k46 "true"
#define _k57 "false"
  //  MODULE
#define _k58 "await"
#define _k59 "async"
  //  STRICT MODE
#define _k34 "let"
#define _k64 "static"
#define _k72 "package"
#define _k73 "private"
#define _k65 "public"
#define _k90 "protected"
#define _k91 "interface"
#define _k101 "implements"

  //  FUTURE RESERVED WORDS
#define _k47 "enum"
